# Generated by Django 4.1.4 on 2022-12-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('floor_number', models.IntegerField(default=1)),
                ('room_number', models.IntegerField(default=1)),
            ],
        ),
    ]
