# Generated by Django 4.1.4 on 2023-01-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offers_duration_offers_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
