# Generated by Django 4.1.4 on 2023-01-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_devise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='profile_pic',
            new_name='Card',
        ),
        migrations.AddField(
            model_name='offers',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='devise',
            field=models.ManyToManyField(to='offers.devise'),
        ),
        migrations.AddField(
            model_name='offers',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='status',
            field=models.CharField(choices=[('Sell', 'Sell'), ('buy', 'buy')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='payment',
            field=models.ManyToManyField(to='offers.payment'),
        ),
    ]
