# Generated by Django 4.1.4 on 2023-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offers_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Devise',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='offers',
            name='devise',
            field=models.CharField(choices=[('paysera', 'paysera'), ('wise', 'wise'), ('baridimob', 'baridimob')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='payment',
            field=models.CharField(choices=[('paysera', 'paysera'), ('wise', 'wise'), ('baridimob', 'baridimob')], max_length=200, null=True),
        ),
    ]
