# Generated by Django 4.1.4 on 2023-02-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_remove_offers_devise_remove_offers_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='lowest',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='offers',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
