# Generated by Django 4.1.4 on 2023-02-12 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_offers_lowest_offers_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='devisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='offers',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
