# Generated by Django 4.1.4 on 2023-02-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_devisee_alter_offers_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='devisee',
        ),
    ]
