# Generated by Django 4.1.4 on 2023-02-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_devisee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='devise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.devisee'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='payment',
            field=models.CharField(choices=[('paysera', 'paysera'), ('wise', 'wise')], max_length=200, null=True),
        ),
    ]
