# Generated by Django 4.1.4 on 2023-02-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_alter_offers_devise_alter_offers_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='devise',
            field=models.CharField(choices=[('paysera', 'paysera'), ('wise', 'wise'), ('baridimob', 'baridimob')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='payment',
            field=models.CharField(choices=[('paysera', 'paysera'), ('wise', 'wise'), ('baridimob', 'baridimob')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='devisee',
        ),
    ]
