# Generated by Django 4.1.4 on 2023-02-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_customer_face_picture_alter_offers_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='LinkFb',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
