# Generated by Django 4.1.4 on 2023-02-21 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_customer_linkfb_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
